security:
    encoders: 
        App\Entity\User:
            algorithm:  bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        wordsmith_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: wordsmith_provider

            form_login:
                # route de l'affichage de la page de login
                login_path: security_login
                # route verification du login
                check_path: security_login

            logout:
                # url logout
                path:   /logout
                # url de redirection apres logout
                target: /


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/forum/thread/[0-9]+/new', roles: ROLE_USER }
        - { path: '^/forum/thread/[0-9]+/edit', roles: ROLE_USER }
        - { path: '^/forum/thread/[0-9]+/move', roles: ROLE_MODERATOR } 
        - { path: '^/forum/post', roles: ROLE_USER } 
        - { path: '^/profil', roles: ROLE_USER }
        - { path: ^/room, roles: ROLE_USER } 
        - { path: ^/backend/user, roles: ROLE_ADMINISTRATOR }
        - { path: ^/backend, roles: ROLE_MODERATOR }
    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMINISTRATOR: ROLE_USER, ROLE_MODERATOR
        ROLE_SUPERADMIN: ROLE_USER, ROLE_MODERATOR, ROLE_ADMINISTRATOR
